/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat;

import ParabitModel.PbtHHModel;
import java.awt.Color;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.border.Border;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.Document;

/**
 *
 * @author Asus
 */
public class PbtHHOthersDetails extends javax.swing.JDialog implements ItemListener,DocumentListener{

    /**
     * Creates new form PbtHHOthersDetails
     */
    PbtSingleMemberDashBoard dashBoard;
    PbtHHModel hhmodel;
    Border defaultborder,errorborder;
    public PbtHHOthersDetails(PbtSingleMemberDashBoard parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.dashBoard=parent;
        this.hhmodel=parent.hhmodel;
        nri1.addItemListener(this);
        nri2.addItemListener(this);
        reasonmig.setVisible(false);
        rmig.setVisible(false);
        lerror.setVisible(false);
        timemigr.setVisible(false);
        tmig.setVisible(false);
        foreginadd.setVisible(false);
        fadd.setVisible(false);
        pmtpin.getDocument().addDocumentListener(this);
        timemigr.getDocument().addDocumentListener(this);
        defaultborder=pmtpin.getBorder();
        errorborder= BorderFactory.createLineBorder(Color.red, 2);
        setDataModel();
        
    }
    private void setDataModel()
    {
        birthplace.setText(hhmodel.getBirthPlaceWithStateCountry());
        pmthouse.setText(hhmodel.getPmtHNoAdd());
        pmtward.setText(hhmodel.getPmtWardNo());
        pmttown.setText(hhmodel.getPmtTownVillage());
        pmttehsil.setText(hhmodel.getPmtTehsil());
        pmtdist.setText(hhmodel.getPmtDist());
        pmtpin.setText(hhmodel.getPmtPinCode());
        pmtstate.setText(hhmodel.getPmtStUt());
        foreginadd.setText(hhmodel.getForeignAdd());
        reasonmig.setText(hhmodel.getRsnOfMig());
        timemigr.setText(hhmodel.getDurOfMig());
        if(hhmodel.getNri()!=null)
        {
            if(hhmodel.getNri().equals("Y"))
                nri1.setSelected(true);
            else if(hhmodel.getNri().equals("N"))
                nri2.setSelected(true);
        }
    }
    private void setModel()
    {
        hhmodel.setBirthPlaceWithStateCountry(birthplace.getText());
        hhmodel.setPmtHNoAdd(pmthouse.getText());
        hhmodel.setPmtWardNo(pmtward.getText());
        hhmodel.setPmtTownVillage(pmttown.getText());
        hhmodel.setPmtTehsil(pmttehsil.getText());
        hhmodel.setPmtDist(pmtdist.getText());
        hhmodel.setPmtPinCode(pmtpin.getText());
        hhmodel.setPmtStUt(pmtstate.getText());
        hhmodel.setForeignAdd(foreginadd.getText());
        hhmodel.setRsnOfMig(reasonmig.getText());
        hhmodel.setDurOfMig(timemigr.getText());
        if(nri1.isSelected())
            hhmodel.setNri("Y");
        else if(nri2.isSelected())
            hhmodel.setNri("N");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        birthplace = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pmtstate = new javax.swing.JTextField();
        pmtdist = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pmttehsil = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pmttown = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pmtward = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        pmtpin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pmthouse = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        nri1 = new javax.swing.JRadioButton();
        nri2 = new javax.swing.JRadioButton();
        fadd = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        foreginadd = new javax.swing.JTextArea();
        rmig = new javax.swing.JLabel();
        reasonmig = new javax.swing.JTextField();
        tmig = new javax.swing.JLabel();
        timemigr = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        lerror = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Birth Place with State & Country :");

        jLabel3.setText("State :");

        jLabel4.setText("District :");

        jLabel5.setText("Tehsil :");

        jLabel6.setText("Town / Village :");

        jLabel7.setText("Ward No :");

        jLabel8.setText("PinCode :");

        jLabel9.setText("House No/Street/Locality :");

        pmthouse.setColumns(20);
        pmthouse.setRows(5);
        jScrollPane1.setViewportView(pmthouse);

        jLabel10.setText("Permanent Address Details");

        jLabel11.setText("NRI :");

        buttonGroup1.add(nri1);
        nri1.setText("Yes");

        buttonGroup1.add(nri2);
        nri2.setText("No");

        fadd.setText("Foreign Address :");

        foreginadd.setColumns(20);
        foreginadd.setRows(5);
        jScrollPane2.setViewportView(foreginadd);

        rmig.setText("Reason of Migration :");

        tmig.setText("Time Period of Migration :");

        savebtn.setText("Save and Back");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Other Misc Details");

        lerror.setForeground(new java.awt.Color(255, 0, 0));
        lerror.setText("Invalid data in head registered mobile no");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(18, 18, 18)
                                            .addComponent(pmtward, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(18, 18, 18)
                                            .addComponent(pmttown, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(18, 18, 18)
                                            .addComponent(pmttehsil, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(pmtdist, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(18, 18, 18)
                                            .addComponent(pmtpin, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(pmtstate, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(18, 18, 18)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel10)
                                                .addComponent(jLabel2))
                                            .addGap(18, 18, 18)
                                            .addComponent(birthplace, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(172, 172, 172)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(fadd)
                                    .addComponent(rmig)
                                    .addComponent(tmig))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timemigr, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(savebtn)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(nri1)
                                                .addGap(18, 18, 18)
                                                .addComponent(nri2))
                                            .addComponent(jScrollPane2)
                                            .addComponent(reasonmig, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lerror))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(461, 461, 461)
                                .addComponent(jLabel1)))
                        .addGap(0, 55, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(birthplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel10)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(nri1)
                        .addComponent(nri2)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(pmtward, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fadd))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(pmttown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(pmttehsil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rmig)
                            .addComponent(reasonmig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(pmtdist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tmig)
                            .addComponent(timemigr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(pmtpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(pmtstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lerror)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
       setModel();
       Map<Object,Object> data=new HashMap();
       data.put("nri",hhmodel.getNri());
       data.put("foreignadd",hhmodel.getForeignAdd());
       data.put("birthPlaceWithStateCountry",hhmodel.getBirthPlaceWithStateCountry());
       data.put("pmtstut",hhmodel.getPmtStUt());
       data.put("pmtdist",hhmodel.getPmtDist());
       data.put("pmttehsil",hhmodel.getPmtTehsil());
       data.put("pmttownvillage",hhmodel.getPmtTownVillage());
       data.put("pmtwardno",hhmodel.getPmtWardNo());
       data.put("pmthnoadd",hhmodel.getPmtHNoAdd());
       data.put("pmtpincode",hhmodel.getPmtPinCode());
       data.put("rsnofmig",hhmodel.getRsnOfMig());
       data.put("durofmig",hhmodel.getDurOfMig());
       hhmodel.myQuery(data);
       dashBoard.hhmodel=hhmodel;
       dispose();
    }//GEN-LAST:event_savebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PbtHHOthersDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PbtHHOthersDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PbtHHOthersDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PbtHHOthersDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField birthplace;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel fadd;
    private javax.swing.JTextArea foreginadd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lerror;
    private javax.swing.JRadioButton nri1;
    private javax.swing.JRadioButton nri2;
    private javax.swing.JTextField pmtdist;
    private javax.swing.JTextArea pmthouse;
    private javax.swing.JTextField pmtpin;
    private javax.swing.JTextField pmtstate;
    private javax.swing.JTextField pmttehsil;
    private javax.swing.JTextField pmttown;
    private javax.swing.JTextField pmtward;
    private javax.swing.JTextField reasonmig;
    private javax.swing.JLabel rmig;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField timemigr;
    private javax.swing.JLabel tmig;
    // End of variables declaration//GEN-END:variables

    @Override
    public void itemStateChanged(ItemEvent e) {
        if(e.getSource()==nri1)
        {
            reasonmig.setVisible(true);
            rmig.setVisible(true);
            timemigr.setVisible(true);
            tmig.setVisible(true);
            foreginadd.setVisible(true);
            fadd.setVisible(true);
        }else if(e.getSource()==nri2)
        {
            reasonmig.setVisible(false);
            rmig.setVisible(false);
            timemigr.setVisible(false);
            tmig.setVisible(false);
            foreginadd.setVisible(false);
            fadd.setVisible(false);
        }
    }
    private boolean checkNum(String str)
    {
        Pattern p=Pattern.compile("[a-zA-z]");
        Matcher mat=p.matcher(str);
        return mat.find();
    }
    private void setNoError(javax.swing.JTextField nob)
    {
        nob.setBorder(defaultborder);
        lerror.setVisible(false);
        savebtn.setEnabled(true);
    }
    private void setError(javax.swing.JTextField nob)
    {
        nob.setBorder(errorborder);
        lerror.setText("Invalid data in some fields");
        lerror.setVisible(true);
        savebtn.setEnabled(false);
    }
    private void verifyNum(DocumentEvent e)
    {
        if(e.getDocument()==pmtpin.getDocument())
        {
            String pin=pmtpin.getText();
            if(!checkNum(pin)&& pin.length()==6)
            {
                setNoError(pmtpin);
            }
            else
            {
                setError(pmtpin);
            }
        }
        else if(e.getDocument()==timemigr.getDocument())
        {
            String time=timemigr.getText();
            if(!checkNum(time)&& time.length()==1||time.length()==2)
            {
                setNoError(timemigr);
            }
            else
            {
                setError(timemigr);
            }
        
        }
        
    }
    
    @Override
    public void insertUpdate(DocumentEvent e) {
        verifyNum(e);
      }

    @Override
    public void removeUpdate(DocumentEvent e) {
        verifyNum(e);
    }

    @Override
    public void changedUpdate(DocumentEvent e) {
    }
}
