/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat;

import ParabitModel.PbtHHModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Asus
 */
public class PbtHapinessQuestions extends javax.swing.JDialog {

    /**
     * Creates new form JTestFrame
     */
    /*public PbtHapinessQuestions(String s)
    {
        SwingUtilities.invokeLater(()->{
            //createGUI();
        });
    }*/
    static PbtHapinessQuestions myFrame;
    ArrayList<String> questions,questionno;
    public PbtHapinessQuestions(PbtSingleMemberDashBoard parent,PbtHHModel hhmodel)
    {
        SwingUtilities.invokeLater(()->{
            createGUI(parent,hhmodel);
        });
    }
    public PbtHapinessQuestions(PbtSingleMemberDashBoard parent) {
        super(parent,true);
        initComponents();
    }
    static void createGUI(PbtSingleMemberDashBoard frame,PbtHHModel hhmodel)
    {
        myFrame=new PbtHapinessQuestions(frame);
        myFrame.setLocationRelativeTo(null);
        myFrame.prepareUI(hhmodel);
        myFrame.pack();
        myFrame.setVisible(true);
    }
     private void prepareUI(PbtHHModel hhmodel) {
        namelabel.setText(hhmodel.getName());
        agelabel.setText(hhmodel.getAge()+"");
        mainPanel.setLayout(new BoxLayout(mainPanel, BoxLayout.Y_AXIS));
        int questioncount=0;
        questions=new ArrayList();
        questionno=new ArrayList();
        ParabitDBC db=new ParabitDBC();
        try
        {
            String query="select * from happiness_question";
            query="SELECT * FROM `happiness_question` WHERE min_age<="+hhmodel.getAge()+" and max_age>="+hhmodel.getAge()+"";
            db.rs1=db.stm.executeQuery(query);
            while(db.rs1.next())
            {
                questioncount++;
                questionno.add(db.rs1.getString(1));
                questions.add(db.rs1.getString(2));
            }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
        PbtHapinessQuestionPane nob[]=new PbtHapinessQuestionPane[questioncount];
        for(int i=0;i<questioncount;i++)
        {
            nob[i]=new PbtHapinessQuestionPane(questions.get(i));
            mainPanel.add(nob[i]);
        }
        finalsave.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ParabitDBC db=new ParabitDBC();
                for(int i=0;i<nob.length;i++)
                {
                    String qno=questionno.get(i);
                    String rating=nob[i].jSlider1.getValue()+"";
                    String query="INSERT INTO `happiness_answer`(`HL_Sno`, `HH_SNo`, `Questionnum`, `Rating`, `Status`) VALUES ("+hhmodel.getHlSNo()+","+hhmodel.getHhSNo()+","+qno+","+rating+",'1')";
                    try
                    {
                        System.err.println(""+query);
                        db.stm.execute(query);
                    }catch(Exception ex)
                    {
                        ex.printStackTrace();
                    }
                }
                dispose();
            }
        });
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        finalsave = new javax.swing.JButton();
        namelabel = new javax.swing.JLabel();
        agelabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mainPanel.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1196, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Happiness Questions");

        finalsave.setText("Final Save");

        namelabel.setText("Name");

        agelabel.setText("Age");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(namelabel)
                .addGap(45, 45, 45)
                .addComponent(agelabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(finalsave, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(finalsave, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(namelabel)
                        .addComponent(agelabel))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PbtHapinessQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PbtHapinessQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PbtHapinessQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PbtHapinessQuestions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JTestFrame().setVisible(true);
            }
        });*/
//        SwingUtilities.invokeLater(()->{
//            System.err.println("he");
//            JFrame nob=new JFrame();
//            nob.setSize(500,500);
//            nob.setVisible(true);
//            createGUI(nob);
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agelabel;
    private javax.swing.JButton finalsave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel namelabel;
    // End of variables declaration//GEN-END:variables
}
