/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat;

import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class PbtHLDialogGeneticDisease extends javax.swing.JDialog implements MouseListener {

    /**
     * Creates new form PbtHLDialogGeneticDisease
     */
    DefaultTableModel tablemodel;
    ParabitDBC db;
    boolean flag;
    PbtHLDashBoard dashBoard;
    public PbtHLDialogGeneticDisease(PbtHLDashBoard parent, boolean modal) {
        super(parent, modal);
        initComponents();
        db=new ParabitDBC();
        disease.addMouseListener(this);
        this.dashBoard=parent;
        tablemodel=(DefaultTableModel)disease.getModel();
        setTable();
    }
    public void setTable()
    {
        tablemodel.setRowCount(0);
        int i=0;
        String se=like.getText();
        String query="SELECT * FROM `typesofgeneticdisease` WHERE DiseaseType like '%"+se+"%'";
        try
        {
            db.rs1=db.stm.executeQuery(query);
            while(db.rs1.next())
            {
                Object ob[]={++i,db.rs1.getString("DiseaseType")};
                flag=false;
                tablemodel.addRow(ob);
            }
            if(i==0)
            {
                Object ob[]={++i,se};
                tablemodel.addRow(ob);
                flag=true;
            }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        like = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        disease = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        like.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                likeKeyReleased(evt);
            }
        });

        jLabel1.setText("Search :");

        disease.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sno", "Disease"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(disease);
        if (disease.getColumnModel().getColumnCount() > 0) {
            disease.getColumnModel().getColumn(0).setMinWidth(45);
            disease.getColumnModel().getColumn(0).setMaxWidth(55);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(like, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(like, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void likeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_likeKeyReleased
       setTable();
    }//GEN-LAST:event_likeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PbtHLDialogGeneticDisease.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PbtHLDialogGeneticDisease.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PbtHLDialogGeneticDisease.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PbtHLDialogGeneticDisease.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable disease;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField like;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mouseClicked(MouseEvent e) {
        int row=disease.rowAtPoint(e.getPoint());
        String name=tablemodel.getValueAt(row,1).toString();
        System.out.println(name);
        String query="insert into typesofgeneticdisease(sno,DiseaseType) values (null,'"+name+"')";
        try
        {
            if(flag)
            {
                String[] listoptions = {"Add This Disease","Cancel"};
                String msg="This disease is not our master datebase.\nDo you want to add this to the master data base? Adding will reflect all over the India.";
                msg=msg+"\nBe sure to confirm the disease name as it will be checked by Testers";
                   int option = JOptionPane.showOptionDialog(this,msg,
                  "Confirm Final Save",            
                  JOptionPane.YES_NO_OPTION,
                  JOptionPane.WARNING_MESSAGE,
                  null,     
                  listoptions,
                 null
               );
                 if(option==0)
                 {
                db.stm.execute(query);
                query="select * from typesofgeneticdisease where DiseaseType='"+name+"'";
                db.rs1=db.stm1.executeQuery(query);
                if(db.rs1.next())
                    dashBoard.hlmodel.setGenDiss(db.rs1.getString("Sno"));
                 }else
                 {
                     return;
                 }
            }
            else
            {
               int opt=JOptionPane.showConfirmDialog(null, "Add this to the current Houselisting as Genetic Disease?", "Confirm Disease", JOptionPane.YES_NO_OPTION); 
               if(opt==0)
               {
                   query="select * from typesofgeneticdisease where DiseaseType='"+name+"'";
                    db.rs1=db.stm1.executeQuery(query);
                    if(db.rs1.next())
                     dashBoard.hlmodel.setGenDiss(db.rs1.getString("Sno"));
               }else
                   return;
            }
        }catch(Exception ex)
        {
            ex.printStackTrace();
        }
        dispose();
    }

    @Override
    public void mousePressed(MouseEvent e) {
    }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
    }
}
