/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat;

import ParabitModel.PbtHHModel;
import ParabitModel.PbtModelAadhar;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Asus
 */
public class PbtHHBasicDetails extends javax.swing.JDialog {

    /**
     * Creates new form PbtHHBasicDetails
     */
    PbtHHModel hhmodel;
    PbtSingleMemberDashBoard dashboard;
    public PbtHHBasicDetails(PbtSingleMemberDashBoard parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.hhmodel=parent.hhmodel;
        this.dashboard=parent;
        setExistingData();
    }
    private void setExistingData()
    {
        m1.setVisible(false);
        m2.setVisible(false);
        marriageage.setVisible(false);
        mstatus.setVisible(false);
        aprxage.setVisible(false);
        mobno.setText(hhmodel.getMobNo());
        dob.setDate(hhmodel.getDob());
        email.setText(hhmodel.getEmail());
        age.setText(hhmodel.getAge()+"");
        if(hhmodel.getGender().equals("M"))
        {
            gen1.setSelected(true);
            if(hhmodel.getAge()>=21)
            {
                m1.setVisible(true);
                m2.setVisible(true);
                marriageage.setVisible(true);
                mstatus.setVisible(true);
                aprxage.setVisible(true);
                if(hhmodel.getAproMarriageAge()!=null)
                {
                    m1.setSelected(true);
                    marriageage.setText(""+hhmodel.getAproMarriageAge());
                }
            }
        }
        else if(hhmodel.getGender().equals("F"))
        {
            gen2.setSelected(true);
            if(hhmodel.getAge()>=18)
            {
                m1.setVisible(true);
                m2.setVisible(true);
                marriageage.setVisible(true);
                mstatus.setVisible(true);
                aprxage.setVisible(true);
                if(hhmodel.getAproMarriageAge()!=null)
                {
                    m1.setSelected(true);
                    marriageage.setText(""+hhmodel.getAproMarriageAge());
                }
            }
        }
        else
        {
            gen3.setSelected(true);
        }
        reltohead.setText(hhmodel.getRelToHead());
        headuid.setText(hhmodel.getHeadUid());
        headregmobno.setText(hhmodel.getHeadRegMobNo());
        mobno.setText(hhmodel.getMobNo());
        altphoneno.setText(hhmodel.getAltPhoneNo());
        email.setText(hhmodel.getEmail());
        marriageage.setText(hhmodel.getAproMarriageAge());
        religion.setText(hhmodel.getReligion());
        category.setText(hhmodel.getCategory());
        community.setText(hhmodel.getCommunity());
        cast.setText(hhmodel.getCast());
        mtongue.setText(hhmodel.getMTongue());
        rwlang.setText(hhmodel.getRwLang());
        homelang.setText(hhmodel.getHomeLang());
        chdnevenborn.setText(hhmodel.getChdnEvenBorn());
        chdnsurv.setText(hhmodel.getChdnSurv());
        
    }
    private void getAllData()
    {
        hhmodel.setRelToHead(reltohead.getText());
        hhmodel.setHeadUid(headuid.getText());
        hhmodel.setHeadRegMobNo(headregmobno.getText());
        hhmodel.setMobNo(mobno.getText());
        hhmodel.setAltPhoneNo(altphoneno.getText());
        hhmodel.setEmail(email.getText());
        hhmodel.setAproMarriageAge(marriageage.getText());
        hhmodel.setAge(Long.parseLong(age.getText()));
        hhmodel.setReligion(religion.getText());
        hhmodel.setCommunity(community.getText());
        hhmodel.setCategory(category.getText());
        hhmodel.setCast(cast.getText());
        hhmodel.setMTongue(mtongue.getText());
        hhmodel.setRwLang(rwlang.getText());
        hhmodel.setHomeLang(homelang.getText());
        hhmodel.setChdnEvenBorn(chdnevenborn.getText());
        hhmodel.setChdnSurv(chdnsurv.getText());
        if(m1.isSelected())
            hhmodel.setGender("M");
        else if(m2.isSelected())
            hhmodel.setGender("F");
        else
            hhmodel.setGender("O");
        if(m1.isSelected())
            hhmodel.setMarStatus("Y");
        else
            hhmodel.setMarStatus("N");
        Date date=dob.getDate();
        java.sql.Date dobsql=new java.sql.Date(date.getTime());
        hhmodel.setDob(dobsql);
        
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mobno = new javax.swing.JTextField();
        altphoneno = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        religion = new javax.swing.JTextField();
        community = new javax.swing.JTextField();
        category = new javax.swing.JTextField();
        cast = new javax.swing.JTextField();
        dob = new com.toedter.calendar.JDateChooser();
        gen1 = new javax.swing.JRadioButton();
        gen2 = new javax.swing.JRadioButton();
        gen3 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        reltohead = new javax.swing.JTextField();
        headuid = new javax.swing.JTextField();
        headregmobno = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        mtongue = new javax.swing.JTextField();
        rwlang = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        homelang = new javax.swing.JTextField();
        m1 = new javax.swing.JRadioButton();
        m2 = new javax.swing.JRadioButton();
        aprxage = new javax.swing.JLabel();
        marriageage = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        chdnevenborn = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        chdnsurv = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        age = new javax.swing.JTextField();
        mstatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Mobile No :");

        jLabel2.setText("Alternative Mobile No :");

        jLabel3.setText("Date of Birth :");

        jLabel4.setText("Gender :");

        jLabel5.setText("Email :");

        jLabel6.setText("Religion :");

        jLabel7.setText("Community :");

        jLabel8.setText("Category :");

        jLabel10.setText("Cast :");

        cast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                castActionPerformed(evt);
            }
        });

        buttonGroup1.add(gen1);
        gen1.setText("Male");

        buttonGroup1.add(gen2);
        gen2.setText("Female");

        buttonGroup1.add(gen3);
        gen3.setText("Others");

        jLabel12.setText("Relation to Head :");

        jLabel13.setText("Head UID :");

        jLabel14.setText("Head Registered Mobile No :");

        jLabel15.setText("Mother Tounge :");

        jLabel16.setText("Read Write Language :");

        jLabel17.setText("Home Language :");

        buttonGroup2.add(m1);
        m1.setText("Married");

        buttonGroup2.add(m2);
        m2.setText("Unmarried");

        aprxage.setText("Approx Marriage Age :");

        jLabel9.setText("Child Born :");

        jLabel11.setText("No of Childern Survived :");

        jButton1.setText("Save and Proceed");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel18.setText("Age :");

        mstatus.setText("Marriage Status :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(aprxage)
                            .addComponent(mstatus))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(m1)
                                                .addGap(18, 18, 18)
                                                .addComponent(m2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel11))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(mobno, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                                                .addComponent(altphoneno)
                                                                .addComponent(email))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(gen1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(gen2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(gen3)))
                                                        .addGap(183, 183, 183))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(headuid)
                                                            .addComponent(headregmobno, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                                            .addComponent(reltohead))
                                                        .addGap(190, 190, 190))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(87, 87, 87)
                                                        .addComponent(jLabel18)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel15)
                                                    .addComponent(jLabel16)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel9))))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cast, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                            .addComponent(mtongue)
                                            .addComponent(rwlang)
                                            .addComponent(community)
                                            .addComponent(category)
                                            .addComponent(religion)
                                            .addComponent(homelang)
                                            .addComponent(chdnevenborn)
                                            .addComponent(chdnsurv))))
                                .addGap(52, 52, 52))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(marriageage, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(reltohead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(headuid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(headregmobno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(mobno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(altphoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(gen1)
                            .addComponent(gen2)
                            .addComponent(gen3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(m1)
                                    .addComponent(mstatus))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(aprxage)
                                    .addComponent(marriageage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(m2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(religion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(community, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mtongue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rwlang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(homelang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(chdnevenborn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(chdnsurv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(4, 4, 4)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void castActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_castActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_castActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getAllData();
        Map<Object,Object> data = new HashMap();
        data.put("reltohead",hhmodel.getRelToHead());
        data.put("headuid",hhmodel.getHeadUid());
        data.put("headregmobno",hhmodel.getHeadRegMobNo());
        data.put("mobno",hhmodel.getMobNo());
        data.put("altphoneno",hhmodel.getAltPhoneNo());
        data.put("email",hhmodel.getEmail());
        data.put("marriagestatus",hhmodel.getMarStatus());
        data.put("marriageage",hhmodel.getAproMarriageAge());
        data.put("religion",hhmodel.getReligion());
        data.put("category",hhmodel.getCategory());
        data.put("community",hhmodel.getCommunity());
        data.put("cast",hhmodel.getCast());
        data.put("mtongue",hhmodel.getMTongue());
        data.put("rwlang",hhmodel.getRwLang());
        data.put("homelang",hhmodel.getHomeLang());
        data.put("chdnevenborn",hhmodel.getChdnEvenBorn());
        data.put("chdnsurv",hhmodel.getChdnSurv());
        data.put("dob",hhmodel.getDob());
        hhmodel.myQuery(data);
        dashboard.hhmodel=hhmodel;
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PbtHHBasicDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PbtHHBasicDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PbtHHBasicDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PbtHHBasicDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JTextField altphoneno;
    private javax.swing.JLabel aprxage;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField cast;
    private javax.swing.JTextField category;
    private javax.swing.JTextField chdnevenborn;
    private javax.swing.JTextField chdnsurv;
    private javax.swing.JTextField community;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField email;
    private javax.swing.JRadioButton gen1;
    private javax.swing.JRadioButton gen2;
    private javax.swing.JRadioButton gen3;
    private javax.swing.JTextField headregmobno;
    private javax.swing.JTextField headuid;
    private javax.swing.JTextField homelang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton m1;
    private javax.swing.JRadioButton m2;
    private javax.swing.JTextField marriageage;
    private javax.swing.JTextField mobno;
    private javax.swing.JLabel mstatus;
    private javax.swing.JTextField mtongue;
    private javax.swing.JTextField religion;
    private javax.swing.JTextField reltohead;
    private javax.swing.JTextField rwlang;
    // End of variables declaration//GEN-END:variables
}
