/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parabitccasbharat;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class PbtNotification extends javax.swing.JDialog {

    /**
     * Creates new form PbtNotification
     */
    ParabitDBC db;
    PbtEmpDashBoard pbtempdashboard;
    public PbtNotification(PbtEmpDashBoard parent, boolean modal) {
        super(parent, modal);      
        initComponents();
        setLocationRelativeTo(null);
        db=new ParabitDBC();
        this.pbtempdashboard=parent;
        getNotifications();
    }
    private void getNotifications()
    {
        DefaultTableModel ob=new DefaultTableModel();
        ob=(DefaultTableModel)notification.getModel();
        ob.setRowCount(0);
        try
        {
            String query="select * from pbtnotification where recieverceid='"+pbtempdashboard.empdata.getEmpid()+"' or senderceid='"+pbtempdashboard.empdata.getEmpid()+"'";
            db.rs1=db.stm.executeQuery(query);
            while(db.rs1.next())
            {
             Object obj[]={db.rs1.getString("notid"),db.rs1.getString("senderceid"),db.rs1.getString("time"),db.rs1.getString("Message")};
             ob.addRow(obj);
            }   
        }catch(Exception e)
        {
            System.out.println("Error in notification fetch"+e);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        notification = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup2.add(r1);
        r1.setText("Individual Message");
        r1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r1ActionPerformed(evt);
            }
        });

        buttonGroup2.add(r2);
        r2.setText("Lower Chain Message");
        r2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r2ActionPerformed(evt);
            }
        });

        buttonGroup2.add(r3);
        r3.setText("Common Notification");
        r3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Send Notification Area");

        notification.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Notification ID", "SenderCEID", "Time", "Message"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(notification);
        if (notification.getColumnModel().getColumnCount() > 0) {
            notification.getColumnModel().getColumn(0).setMinWidth(80);
            notification.getColumnModel().getColumn(0).setMaxWidth(85);
            notification.getColumnModel().getColumn(1).setMinWidth(150);
            notification.getColumnModel().getColumn(1).setMaxWidth(160);
            notification.getColumnModel().getColumn(2).setMinWidth(160);
            notification.getColumnModel().getColumn(2).setMaxWidth(170);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(r1)
                        .addGap(180, 180, 180)
                        .addComponent(r2)
                        .addGap(206, 206, 206)
                        .addComponent(r3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(r1)
                    .addComponent(r2)
                    .addComponent(r3))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r1ActionPerformed
        setVisible(false);
        PbtEmployeeSummary nob=new PbtEmployeeSummary(pbtempdashboard, true,2);
        nob.setVisible(true);
        setVisible(true);
    }//GEN-LAST:event_r1ActionPerformed

    private void r2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r2ActionPerformed
        setVisible(false);
        PbtAppointedEmployee nob=new PbtAppointedEmployee(pbtempdashboard, true,2);
        nob.setVisible(true);
        setVisible(true);
    }//GEN-LAST:event_r2ActionPerformed

    private void r3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r3ActionPerformed
        PbtMessageFrame nob=new PbtMessageFrame(pbtempdashboard, true, 3);
        nob.setLocationRelativeTo(null);
        nob.setName("common","common");
        nob.setVisible(true);
    }//GEN-LAST:event_r3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable notification;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    // End of variables declaration//GEN-END:variables
}
